---
title: "Linear Algebra"
output:
  html_document:
    highlight: pygments
    keep_md: yes
---

### How do I create a matrix?

R:
```{r matrix-R}
a <- matrix(c(1,2,3,11,12,13), nrow=2, ncol=3, byrow=TRUE) # fill values by row
a
```

Python:
```{r matrix-python, engine='python'}
import numpy as np
a = np.matrix([[1,2,3],[11,12,13]])
print a
```

### How do I find the dimension of a matrix?

R:
```{r dim-R}
a <- matrix(c(1,2,3,11,12,13), nrow=2, ncol=3, byrow=TRUE) # fill values by row
dim(a) # shows row x column dimension
```

Python:
```{r dim-python, engine='python'}
import numpy as np
a = np.matrix([[1,2,3],[11,12,13]])
print a.shape # shows row x column dimension
```


### How do I perform matrix multiplication?

R:
```{r matmul-R}
a <- matrix(c(1,2,3), nrow=1)
b <- matrix(c(1,1,1), ncol=1)
a
b
a%*%b
```

Python:
```{r matmul-python, engine='python'}
import numpy as np
a = np.matrix([1,2,3])
b = np.matrix([[1],[1],[1]])
print "a:"
print a
print "b:"
print b
print "a dot b"
print a*b
print "a dot b with numpy method"
print np.dot(a,b)
```

### How do I transpose a matrix?

R:
```{r transpose-r}
a <- matrix(c(1,2,3), nrow=1)
a
t(a)
```

Python:
```{r transpose-python, engine='python'}
import numpy as np
a = np.matrix([1,2,3])
print a
print a.T
```

### How do I bind rows of vectors/matrices?

R:
```{r, rbind-r}
a <- matrix(c(1,2,3,11,12,13), nrow=2, byrow=TRUE)
b <- c(21,22,23)
a
b
rbind(a,b)
```

Python:
```{r rbind-python, engine='python'}
import numpy as np
a = np.matrix([[1,2,3],[11,12,13]])
b = np.matrix([[21,22,23]])
print a
print b
print np.vstack((a,b))
```

### How do I bind columns?

R:
```{r, cbind-r}
a <- matrix(c(1,11,2,12,3,13), nrow=3, ncol=2, byrow=TRUE)
b <- matrix(c(21,22,23), ncol=1)
a
b
cbind(a,b)
```

Python:
```{r cbind-python, engine='python'}
import numpy as np
a = np.matrix([[1,11],[2,12],[3,13]])
b = np.matrix([[21],[22],[23]])
print "a:"
print a
print "b:"
print b
print "after hstack:"
print np.hstack((a,b))
```